# Generated by Django 5.2.4 on 2025-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите заголовок', max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, default='содержимое нет', help_text='Введите содержимое', max_length=5000, null=True, verbose_name='содержимое')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото', null=True, upload_to='blog/photo', verbose_name='изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('sign_publication', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('watch_count', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ['name', 'watch_count'],
            },
        ),
    ]
